// Copyright (C) 2022-2024, Chain4Travel AG. All rights reserved.
//
// This file is a derived work, based on ava-labs code whose
// original notices appear below.
//
// It is distributed under the same license conditions as the
// original code from which it is derived.
//
// Much love to the original authors for their work.
// **********************************************************
// Copyright (C) 2019-2024, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

package txs

import (
	"math"
	"time"

	"github.com/ava-labs/avalanchego/codec"
	"github.com/ava-labs/avalanchego/codec/linearcodec"
	"github.com/ava-labs/avalanchego/utils/wrappers"
	"github.com/ava-labs/avalanchego/vms/components/multisig"
	"github.com/ava-labs/avalanchego/vms/platformvm/dac"
	"github.com/ava-labs/avalanchego/vms/platformvm/locked"
	"github.com/ava-labs/avalanchego/vms/platformvm/signer"
	"github.com/ava-labs/avalanchego/vms/platformvm/stakeable"
	"github.com/ava-labs/avalanchego/vms/secp256k1fx"
)

const CodecVersion = 0

var (
	Codec codec.Manager

	// GenesisCodec allows txs of larger than usual size to be parsed.
	// While this gives flexibility in accommodating large genesis txs
	// it must not be used to parse new, unverified txs which instead
	// must be processed by Codec
	GenesisCodec codec.Manager
)

// TODO: Remove after v1.11.x has activated
//
// Invariant: InitCodec, Codec, and GenesisCodec must not be accessed
// concurrently
func InitCodec(durangoTime time.Time) error {
	c := linearcodec.NewCaminoDefault(durangoTime)
	gc := linearcodec.NewCaminoCustomMaxLength(time.Time{}, math.MaxInt32)

	errs := wrappers.Errs{}
	for _, c := range []linearcodec.CaminoCodec{c, gc} {
		// Order in which type are registered affect the byte representation
		// generated by marshalling ops. To maintain codec type ordering,
		// we skip positions for the blocks.
		c.SkipRegistrations(5)

		errs.Add(RegisterUnsignedTxsTypes(c))

		c.SkipRegistrations(4)

		errs.Add(RegisterDUnsignedTxsTypes(c))
	}

	newCodec := codec.NewDefaultManager()
	newGenesisCodec := codec.NewManager(math.MaxInt32)
	errs.Add(
		newCodec.RegisterCodec(CodecVersion, c),
		newGenesisCodec.RegisterCodec(CodecVersion, gc),
	)
	if errs.Errored() {
		return errs.Err
	}

	Codec = newCodec
	GenesisCodec = newGenesisCodec
	return nil
}

func init() {
	if err := InitCodec(time.Time{}); err != nil {
		panic(err)
	}
}

// RegisterUnsignedTxsTypes allows registering relevant type of unsigned package
// in the right sequence. Following repackaging of platformvm package, a few
// subpackage-level codecs were introduced, each handling serialization of
// specific types.
//
// RegisterUnsignedTxsTypes is made exportable so to guarantee that other codecs
// are coherent with components one.
func RegisterUnsignedTxsTypes(targetCodec linearcodec.CaminoCodec) error {
	errs := wrappers.Errs{}

	// The secp256k1fx is registered here because this is the same place it is
	// registered in the AVM. This ensures that the typeIDs match up for utxos
	// in shared memory.
	errs.Add(targetCodec.RegisterType(&secp256k1fx.TransferInput{}))
	targetCodec.SkipRegistrations(1)
	errs.Add(targetCodec.RegisterType(&secp256k1fx.TransferOutput{}))
	targetCodec.SkipRegistrations(1)
	errs.Add(
		targetCodec.RegisterType(&secp256k1fx.Credential{}),
		targetCodec.RegisterType(&secp256k1fx.Input{}),
		targetCodec.RegisterType(&secp256k1fx.OutputOwners{}),

		targetCodec.RegisterType(&AddValidatorTx{}),
		targetCodec.RegisterType(&AddSubnetValidatorTx{}),
		targetCodec.RegisterType(&AddDelegatorTx{}),
		targetCodec.RegisterType(&CreateChainTx{}),
		targetCodec.RegisterType(&CreateSubnetTx{}),
		targetCodec.RegisterType(&ImportTx{}),
		targetCodec.RegisterType(&ExportTx{}),
		targetCodec.RegisterType(&AdvanceTimeTx{}),
		targetCodec.RegisterType(&RewardValidatorTx{}),

		targetCodec.RegisterType(&stakeable.LockIn{}),
		targetCodec.RegisterType(&stakeable.LockOut{}),

		// Banff additions:
		targetCodec.RegisterType(&RemoveSubnetValidatorTx{}),
		targetCodec.RegisterType(&TransformSubnetTx{}),
		targetCodec.RegisterType(&AddPermissionlessValidatorTx{}),
		targetCodec.RegisterType(&AddPermissionlessDelegatorTx{}),

		targetCodec.RegisterType(&signer.Empty{}),
		targetCodec.RegisterType(&signer.ProofOfPossession{}),

		// Camino custom types
		targetCodec.RegisterCustomType(&locked.In{}),
		targetCodec.RegisterCustomType(&locked.Out{}),

		targetCodec.RegisterCustomType(&CaminoAddValidatorTx{}),
		targetCodec.RegisterCustomType(&CaminoRewardValidatorTx{}),
		targetCodec.RegisterCustomType(&AddressStateTx{}),
		targetCodec.RegisterCustomType(&DepositTx{}),
		targetCodec.RegisterCustomType(&UnlockDepositTx{}),
		targetCodec.RegisterCustomType(&RegisterNodeTx{}),
		targetCodec.RegisterCustomType(&BaseTx{}),
		targetCodec.RegisterCustomType(&MultisigAliasTx{}),
		targetCodec.RegisterCustomType(&ClaimTx{}),
		targetCodec.RegisterCustomType(&RewardsImportTx{}),
		targetCodec.RegisterCustomType(&secp256k1fx.MultisigCredential{}),
		targetCodec.RegisterCustomType(&multisig.AliasWithNonce{}),
		targetCodec.RegisterCustomType(&secp256k1fx.CrossTransferOutput{}),
		targetCodec.RegisterCustomType(&AddDepositOfferTx{}),
		targetCodec.RegisterCustomType(&AddProposalTx{}),
		targetCodec.RegisterCustomType(&AddVoteTx{}),
		targetCodec.RegisterCustomType(&FinishProposalsTx{}),
		targetCodec.RegisterCustomType(&dac.BaseFeeProposal{}),
		targetCodec.RegisterCustomType(&dac.DummyVote{}),
		targetCodec.RegisterCustomType(&dac.SimpleVote{}),
		targetCodec.RegisterCustomType(&dac.AddMemberProposal{}),
		targetCodec.RegisterCustomType(&dac.AdminProposal{}),
		targetCodec.RegisterCustomType(&dac.ExcludeMemberProposal{}),
		targetCodec.RegisterCustomType(&dac.GeneralProposal{}),
		targetCodec.RegisterCustomType(&dac.FeeDistributionProposal{}),
	)
	return errs.Err
}

func RegisterDUnsignedTxsTypes(targetCodec linearcodec.Codec) error {
	return targetCodec.RegisterType(&TransferSubnetOwnershipTx{})
}
